# Name of your workflow.
name: flutter drive

# Trigger the workflow on push or pull request.
on: [push, pull_request]

env:
  flutter_version: "1.12.13+hotfix.8" # If I was using flutterw this would need to be pulled from flutterw/version to keep things in sync
  CI: github-actions
  DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer

jobs:
  drive:
    strategy:
      matrix:
        device:
        - "iPhone 8 (13.3)" # TODO find a way to handle iOS version changes (e.g. 13.1->13.5)
      fail-fast: true
    timeout-minutes: 20 # Fail after 20 minutes.
    runs-on: macos-10.15

    steps:
    - name: "List all simulators"
      run: "xcrun instruments -s"

    - name: "Start Simulator"
      run: |
        UDID=$(
          xcrun instruments -s |
          awk \
            -F ' *[][]' \
            -v 'device=${{ matrix.device }}' \
            '$1 == device { print $2 }'
        )
        xcrun simctl boot "${UDID:?No Simulator with this name found}"
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Flutter Cache
      uses: actions/cache@v2
      with:
        path: /Users/runner/hostedtoolcache/flutter
        # The cache should reset when we update the version number: 
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }} 
        restore-keys: ${{ runner.OS }}-flutter-install-cache-
    
    - name: Setup Flutter
      uses: subosito/flutter-action@40bc2f
      with:
        flutter-version: ${{ env.flutter_version }}

    - name: Install dependencies
      run: flutter pub get  

    - name: Check Flutter Health
      run: "flutter doctor"

    - name: Run Flutter Driver tests
      run: "flutter drive --target=test_driver/app.dart"  
